name: nukegame
description: A nuke game
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  get_it: ^7.2.0
  dafluta: ^4.4.0
  url_strategy: ^0.2.0
  json_annotation: ^4.7.0
  
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true